services:
  db:
      image: postgres
      volumes:
        - ./data/db:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      env_file:
        - .env
      networks:
        database: {}

networks:
  database:
    external: true