pipeline {
    agent {
        docker { image 'python:3' }
    }

    triggers {
        pollSCM '*/5 * * * *'
    }

    stages {
        stage('Building') {
            steps {
                echo 'Building...'
                sh '''
                    cd backend
                    python3 -m venv env
                    . ./env/bin/activate
                    pip install -r requirements.txt
                '''
            }
        }
        stage('Testing') {
            steps {
                echo 'Testing...'
                sh '''
                    cd backend
                    . ./env/bin/activate
                    python3 manage.py test
                '''
            }
        }
        stage('Deploying') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}
