pipeline {
    agent {
        docker {
            image 'python:3'
        }
    }

    triggers {
        pollSCM '*/5 * * * *'
    }

    environment {
        POSTGRES_DB = credentials('jenkins-postgres-db')
        POSTGRES_USER = credentials('jenkins-postgres-user') 
        POSTGRES_PASSWORD = credentials('jenkins-postgres-password')
        POSTGRES_HOST = credentials('jenkins-postgres-host')
        POSTGRES_PORT = credentials('jenkins-postgres-port')
        DJANGO_SECRET_KEY = credentials('jenkins-django-secret-key')
        NODE_DEPARTMENT_API = credentials('jenkins-node-department-api')
    }

    stages {
        stage('Building') {
            steps {
                echo 'Building...'
                sh '''
                    cd backend
                    python3 -m venv env
                    . ./env/bin/activate
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Setup PostgreSQL') {
            steps {
                echo 'Setting up PostgreSQL...'
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
                        def postgresContainer = docker.image('postgres').run('-p ${POSTGRES_PORT}:5432 -e POSTGRES_DB=${POSTGRES_DB} -e POSTGRES_USER=${POSTGRES_USER} -e POSTGRES_PASSWORD=${POSTGRES_PASSWORD}')
                        echo 'Waiting for PostgreSQL to start...'
                        postgresContainer.waitForLog('database system is ready to accept connections', 300)
                    }
                }
            }
        }

        stage('Testing') {
            steps {
                echo 'Testing...'
                sh '''
                    cd backend
                    . ./env/bin/activate
                    python3 manage.py migrate
                    python3 manage.py test
                '''
            }
        }

        stage('Deploying') {
            steps {
                echo 'Deploying...'
                // Add deployment steps here
            }
        }
    }
}
