# Generated by Django 5.0.1 on 2024-01-23 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0002_alter_employeedepartment_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksfor',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='worksfor',
            name='manager',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.DeleteModel(
            name='EmployeeDepartment',
        ),
        migrations.DeleteModel(
            name='WorksFor',
        ),
    ]
