# Generated by Django 5.0.1 on 2024-01-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='uid',
            new_name='user',
        ),
    ]
