services:
  department-web:
    build: .
    command: yarn start
    volumes:
      - .:/code
    ports:
      - "8090:8090"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    env_file:
      - .env
    networks:
      database: {}

networks:
  database:
    external: true